DROP ROLE NotLoggedClient;
DROP ROLE Client;
DROP ROLE Administrator;

--DROP USER GlobalUser;
--DROP USER SampleClient;
--DROP USER SampleAdmin;

CREATE ROLE NotLoggedClient;
CREATE ROLE Client;
CREATE ROLE Administrator;

GRANT SELECT ON AIRPORT TO NotLoggedClient;
GRANT SELECT ON CITY TO NotLoggedClient;
GRANT SELECT ON CONNECTION TO NotLoggedClient;
GRANT SELECT ON COUNTRY TO NotLoggedClient;
GRANT SELECT ON FLY TO NotLoggedClient;
GRANT SELECT ON RESERVATION TO NotLoggedClient;
GRANT CREATE SESSION TO NotLoggedClient;

GRANT SELECT ANY TABLE TO Client;
GRANT UPDATE ON FLY TO Client;
GRANT INSERT ON RESERVATION TO Client;
GRANT CREATE SESSION TO Client;

GRANT SELECT ANY TABLE, INSERT ANY TABLE, 
	UPDATE ANY TABLE, DELETE ANY TABLE TO Administrator WITH ADMIN OPTION;
GRANT CREATE SESSION TO Administrator;

CREATE USER GlobalUser IDENTIFIED BY asd;
CREATE USER SampleClient IDENTIFIED BY asd;
CREATE USER SampleAdmin IDENTIFIED BY asd;

GRANT NotLoggedClient TO GlobalUser;
GRANT Client TO SampleClient;
GRANT Administrator TO SampleAdmin;